version: '3.3'

services:
  accommodation_service:
    container_name: 'accommodation_service'
    build: './'
    ports:
      - '8080:8080'
    volumes:
      - './:go/src/app'
    depends_on:
      - 'mongo'

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'
    volumes:
      - type: bind
        source: ./data
        target: ./data/db